### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by thaingu** [codersforcauses/bfa-rescue#4]
## Requirements

- Make homepage similar in style and colours as the original site: https://bfarescue.com.au/

## Components

- [x] Navbar and footer - completed in pull request #11
- [ ] About us banner, including information such as what their mission is, where they are located and what they do/what impact do they bring etc.
- [ ] Showcase of dogs/checkout available dogs, dog card contains dog name, age, sex, breed etc. when clicked, link to dog info page
- [ ] Adopt a dog section. Contains brief description about dog adoption, link to the adoption page/form for more details
- [ ] Volunteer section. Contains brief description about getting involved as a volunteer. link to the volunteer section for more details

## Improvements

- Remove the margin for the box-like banner
- Recreate icon as svg, need to consider how the icons match the branding style (sharp edge, round edge etc)

**Comment by definitelyDaphne** [comment]
Some note about redisigning Home page can be found in here https://www.notion.so/codersforcauses/Home-276d991fd9084411b1fc11ad5723fa9a

**Comment by bpgoodwin** [comment]
Ivy Completed this some time ago, closing to clean up issues :)
